version: '3.8'
services:
  app:
    build: .
    image: todo-app:latest
    command: yarn start
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/todoapp
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  seeder:
    build: .
    command: node scripts/seedDB.js
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/todoapp

volumes:
  mongo-data:
