name: CI para aumentar la version

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.12.2'
        
    - name: Install Dependencies
      run: yarn install

    - name: Bump Version
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: yarn bump-version